# Generated by Django 5.2.7 on 2025-10-25 05:33

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('alumnos', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Carrera',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True)),
                ('codigo', models.CharField(max_length=10, unique=True)),
                ('tipo_carrera', models.CharField(choices=[('licenciatura', 'Licenciatura'), ('ingenieria', 'Ingeniería'), ('maestria', 'Maestría'), ('doctorado', 'Doctorado'), ('tecnico', 'Técnico Superior Universitario'), ('especialidad', 'Especialidad')], default='licenciatura', max_length=20)),
                ('numero_semestres', models.PositiveIntegerField(default=8)),
                ('plan', models.PositiveIntegerField(default=2023, validators=[django.core.validators.MinValueValidator(2000), django.core.validators.MaxValueValidator(2030)])),
                ('activa', models.BooleanField(default=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Carrera',
                'verbose_name_plural': 'Carreras',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Unidad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=10)),
                ('nombre', models.CharField(default='', max_length=100)),
                ('numero', models.PositiveIntegerField(default=1)),
                ('carrera', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='unidades', to='evaluaciones.carrera')),
            ],
            options={
                'verbose_name': 'Unidad',
                'verbose_name_plural': 'Unidades',
                'ordering': ['carrera', 'numero'],
                'unique_together': {('carrera', 'codigo')},
            },
        ),
        migrations.CreateModel(
            name='Materia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('semestre', models.PositiveIntegerField()),
                ('creditos', models.FloatField(default=8.0, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(20.0)])),
                ('horas', models.PositiveIntegerField(default=64)),
                ('activa', models.BooleanField(default=True)),
                ('carrera', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='evaluaciones.carrera')),
                ('unidades', models.ManyToManyField(related_name='materias', to='evaluaciones.unidad')),
            ],
            options={
                'verbose_name': 'Materia',
                'verbose_name_plural': 'Materias',
                'ordering': ['carrera', 'semestre', 'nombre'],
                'unique_together': {('carrera', 'nombre', 'semestre')},
            },
        ),
        migrations.CreateModel(
            name='ActaEvaluacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('semestre', models.PositiveIntegerField()),
                ('grupo', models.CharField(max_length=10)),
                ('periodo', models.CharField(max_length=20)),
                ('fecha_generacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_emision', models.DateField()),
                ('estado', models.CharField(choices=[('borrador', 'Borrador'), ('generada', 'Generada'), ('aprobada', 'Aprobada'), ('cerrada', 'Cerrada')], default='borrador', max_length=20)),
                ('archivo_pdf', models.FileField(blank=True, null=True, upload_to='actas/%Y/%m/%d/')),
                ('total_alumnos', models.IntegerField(default=0)),
                ('alumnos_evaluados', models.IntegerField(default=0)),
                ('promedio_grupo', models.DecimalField(decimal_places=2, default=0.0, max_digits=4)),
                ('generada_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('carrera', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='evaluaciones.carrera')),
                ('materia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='evaluaciones.materia')),
            ],
            options={
                'verbose_name': 'Acta de Evaluación',
                'verbose_name_plural': 'Actas de Evaluación',
                'ordering': ['-fecha_generacion'],
                'unique_together': {('materia', 'grupo', 'periodo')},
            },
        ),
        migrations.CreateModel(
            name='PromedioPeriodo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('periodo', models.CharField(max_length=20)),
                ('promedio_general', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('total_materias', models.IntegerField(default=0)),
                ('materias_cursadas', models.IntegerField(default=0)),
                ('materias_aprobadas', models.IntegerField(default=0)),
                ('fecha_calculo', models.DateTimeField(auto_now=True)),
                ('alumno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='alumnos.alumno')),
            ],
            options={
                'verbose_name': 'Promedio de Periodo',
                'verbose_name_plural': 'Promedios de Periodo',
                'ordering': ['alumno', 'periodo'],
                'unique_together': {('alumno', 'periodo')},
            },
        ),
        migrations.CreateModel(
            name='Calificacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('calificacion', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True)),
                ('periodo', models.CharField(max_length=20)),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('alumno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='alumnos.alumno')),
                ('unidad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='evaluaciones.unidad')),
            ],
            options={
                'verbose_name': 'Calificación',
                'verbose_name_plural': 'Calificaciones',
                'ordering': ['alumno', 'unidad__numero'],
                'unique_together': {('alumno', 'unidad', 'periodo')},
            },
        ),
    ]
