# Generated by Django 5.2.6 on 2025-09-30 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ActaEvaluacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('semestre', models.PositiveIntegerField()),
                ('grupo', models.CharField(max_length=10)),
                ('periodo', models.CharField(max_length=20)),
                ('fecha_generacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_emision', models.DateField()),
                ('estado', models.CharField(choices=[('borrador', 'Borrador'), ('generada', 'Generada'), ('aprobada', 'Aprobada'), ('cerrada', 'Cerrada')], default='borrador', max_length=20)),
                ('archivo_pdf', models.FileField(blank=True, null=True, upload_to='actas/%Y/%m/%d/')),
                ('total_alumnos', models.IntegerField(default=0)),
                ('alumnos_evaluados', models.IntegerField(default=0)),
                ('promedio_grupo', models.DecimalField(decimal_places=2, default=0.0, max_digits=4)),
            ],
            options={
                'verbose_name': 'Acta de Evaluación',
                'verbose_name_plural': 'Actas de Evaluación',
                'ordering': ['-fecha_generacion'],
            },
        ),
        migrations.CreateModel(
            name='Calificacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('calificacion', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True)),
                ('periodo', models.CharField(max_length=20)),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Calificación',
                'verbose_name_plural': 'Calificaciones',
                'ordering': ['alumno', 'materia__semestre', 'materia__codigo'],
            },
        ),
        migrations.CreateModel(
            name='Licenciatura',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True)),
                ('codigo', models.CharField(max_length=10, unique=True)),
                ('numero_semestres', models.PositiveIntegerField(default=8)),
                ('plan', models.PositiveIntegerField(default=2023)),
                ('activa', models.BooleanField(default=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Licenciatura',
                'verbose_name_plural': 'Licenciaturas',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Materia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=20)),
                ('nombre', models.CharField(max_length=100)),
                ('semestre', models.PositiveIntegerField()),
                ('creditos', models.PositiveIntegerField(default=0)),
                ('activa', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Materia',
                'verbose_name_plural': 'Materias',
                'ordering': ['licenciatura', 'semestre', 'codigo'],
            },
        ),
        migrations.CreateModel(
            name='PromedioPeriodo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('periodo', models.CharField(max_length=20)),
                ('promedio_general', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('total_materias', models.IntegerField(default=0)),
                ('materias_cursadas', models.IntegerField(default=0)),
                ('materias_aprobadas', models.IntegerField(default=0)),
                ('fecha_calculo', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Promedio de Periodo',
                'verbose_name_plural': 'Promedios de Periodo',
                'ordering': ['alumno', 'periodo'],
            },
        ),
        migrations.CreateModel(
            name='Unidad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=10)),
                ('nombre', models.CharField(default='Unidad', max_length=100)),
                ('numero', models.PositiveIntegerField(default=1)),
            ],
            options={
                'verbose_name': 'Unidad',
                'verbose_name_plural': 'Unidades',
                'ordering': ['licenciatura', 'numero'],
            },
        ),
    ]
