# Generated by Django 5.2.6 on 2025-09-11 20:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('alumnos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Materia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('clave', models.CharField(max_length=20, unique=True)),
                ('licenciatura', models.CharField(choices=[('EDUCACION_ESPECIAL', 'Licenciatura en Educación Especial'), ('INCLUSION_EDUCATIVA', 'Licenciatura en Inclusión Educativa')], max_length=50)),
                ('semestre', models.PositiveIntegerField()),
                ('creditos', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Materia',
                'verbose_name_plural': 'Materias',
                'ordering': ['semestre', 'nombre'],
            },
        ),
        migrations.CreateModel(
            name='ActaEvaluacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('licenciatura', models.CharField(choices=[('EDUCACION_ESPECIAL', 'Licenciatura en Educación Especial'), ('INCLUSION_EDUCATIVA', 'Licenciatura en Inclusión Educativa')], max_length=50)),
                ('semestre', models.PositiveIntegerField()),
                ('grupo', models.CharField(max_length=10)),
                ('periodo', models.CharField(max_length=20)),
                ('fecha_generacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_emision', models.DateField()),
                ('estado', models.CharField(choices=[('borrador', 'Borrador'), ('generada', 'Generada'), ('aprobada', 'Aprobada')], default='borrador', max_length=20)),
                ('archivo_pdf', models.FileField(blank=True, null=True, upload_to='actas/%Y/%m/%d/')),
                ('materia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='evaluaciones.materia')),
            ],
            options={
                'verbose_name': 'Acta de Evaluación',
                'verbose_name_plural': 'Actas de Evaluación',
                'ordering': ['-fecha_generacion'],
            },
        ),
        migrations.CreateModel(
            name='Calificacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('calificacion', models.DecimalField(decimal_places=2, max_digits=4)),
                ('periodo', models.CharField(max_length=20)),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('alumno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='alumnos.alumno')),
                ('materia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='evaluaciones.materia')),
            ],
            options={
                'verbose_name': 'Calificación',
                'verbose_name_plural': 'Calificaciones',
                'ordering': ['alumno', 'materia__semestre'],
                'unique_together': {('alumno', 'materia', 'periodo')},
            },
        ),
    ]
