# Generated by Django 5.2.6 on 2025-10-09 06:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('alumnos', '0002_initial'),
        ('evaluaciones', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='actaevaluacion',
            name='generada_por',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='calificacion',
            name='alumno',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='alumnos.alumno'),
        ),
        migrations.AddField(
            model_name='actaevaluacion',
            name='carrera',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='evaluaciones.carrera'),
        ),
        migrations.AddField(
            model_name='materia',
            name='carrera',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='evaluaciones.carrera'),
        ),
        migrations.AddField(
            model_name='calificacion',
            name='materia',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='evaluaciones.materia'),
        ),
        migrations.AddField(
            model_name='actaevaluacion',
            name='materia',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='evaluaciones.materia'),
        ),
        migrations.AddField(
            model_name='promedioperiodo',
            name='alumno',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='alumnos.alumno'),
        ),
        migrations.AddField(
            model_name='unidad',
            name='carrera',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='unidades', to='evaluaciones.carrera'),
        ),
        migrations.AddField(
            model_name='materia',
            name='unidades',
            field=models.ManyToManyField(related_name='materias', to='evaluaciones.unidad'),
        ),
        migrations.AlterUniqueTogether(
            name='calificacion',
            unique_together={('alumno', 'materia', 'periodo')},
        ),
        migrations.AlterUniqueTogether(
            name='actaevaluacion',
            unique_together={('materia', 'grupo', 'periodo')},
        ),
        migrations.AlterUniqueTogether(
            name='promedioperiodo',
            unique_together={('alumno', 'periodo')},
        ),
        migrations.AlterUniqueTogether(
            name='unidad',
            unique_together={('carrera', 'codigo')},
        ),
        migrations.AlterUniqueTogether(
            name='materia',
            unique_together={('carrera', 'nombre', 'semestre')},
        ),
    ]
