# Generated by Django 5.2.6 on 2025-10-09 07:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evaluaciones', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='materia',
            name='unidades',
        ),
        migrations.AddField(
            model_name='materia',
            name='horas',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='unidad',
            name='materia',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='unidades_asignadas', to='evaluaciones.materia'),
        ),
        migrations.AlterField(
            model_name='materia',
            name='creditos',
            field=models.FloatField(default=0.0),
        ),
    ]
