# Generated by Django 5.2.6 on 2025-10-09 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evaluaciones', '0003_remove_materia_unidades_materia_horas_unidad_materia_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='unidad',
            name='materia',
        ),
        migrations.AddField(
            model_name='materia',
            name='unidades',
            field=models.ManyToManyField(related_name='materias', to='evaluaciones.unidad'),
        ),
    ]
