# Generated by Django 5.2.6 on 2025-10-12 01:07

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evaluaciones', '0004_remove_unidad_materia_materia_unidades'),
    ]

    operations = [
        migrations.AlterField(
            model_name='materia',
            name='creditos',
            field=models.FloatField(default=8.0, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(20.0)]),
        ),
        migrations.AlterField(
            model_name='materia',
            name='horas',
            field=models.PositiveIntegerField(default=64),
        ),
    ]
