# Generated by Django 5.2.6 on 2025-09-11 20:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('alumnos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Constancia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_constancia', models.CharField(choices=[('estudios', 'Constancia de Estudios'), ('calificaciones', 'Constancia de Calificaciones'), ('regular', 'Constancia de Alumno Regular')], max_length=20)),
                ('fecha_generacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_emision', models.DateField()),
                ('estado', models.CharField(choices=[('generada', 'Generada'), ('revisada', 'Revisada'), ('entregada', 'Entregada')], default='generada', max_length=20)),
                ('observaciones', models.TextField(blank=True)),
                ('archivo_pdf', models.FileField(blank=True, null=True, upload_to='constancias/%Y/%m/%d/')),
                ('alumno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='alumnos.alumno')),
            ],
            options={
                'verbose_name': 'Constancia',
                'verbose_name_plural': 'Constancias',
                'ordering': ['-fecha_generacion'],
            },
        ),
    ]
