# Generated by Django 5.2.6 on 2025-09-11 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='usuario',
            options={'verbose_name': 'Usuario', 'verbose_name_plural': 'Usuarios'},
        ),
        migrations.AlterField(
            model_name='usuario',
            name='tipo_usuario',
            field=models.CharField(choices=[('directivo', 'Directivo'), ('control_escolar', 'Control Escolar'), ('docente', 'Docente'), ('alumno', 'Alumno')], default='docente', max_length=20),
        ),
    ]
