# Generated by Django 5.2.6 on 2025-10-12 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='tipo_usuario',
            field=models.CharField(choices=[('directivo', 'Directivo'), ('control_escolar', 'Control Escolar'), ('docente', 'Docente'), ('alumno', 'Alumno')], default='docente', max_length=20),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='turno',
            field=models.CharField(choices=[('matutino', 'Matutino'), ('vespertino', 'Vespertino'), ('ambos turnos', 'Ambos turnos')], default='matutino', max_length=20),
        ),
    ]
