# Generated by Django 5.2.6 on 2025-10-12 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0002_alter_usuario_tipo_usuario_alter_usuario_turno'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='tipo_usuario',
            field=models.CharField(choices=[('directivo', 'Directivo'), ('control_escolar', 'Control Escolar'), ('docente', 'Docente')], default='docente', max_length=20),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='turno',
            field=models.CharField(choices=[('matutino', 'Matutino'), ('vespertino', 'Vespertino')], default='matutino', max_length=20),
        ),
    ]
