# Generated by Django 5.2.6 on 2025-09-12 22:08

import core.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0002_alter_usuario_options_alter_usuario_tipo_usuario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='email',
            field=core.fields.EncryptedEmailField(max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='telefono',
            field=core.fields.EncryptedCharField(blank=True, max_length=15),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='username',
            field=models.CharField(blank=True, help_text='Opcional. 150 caracteres o menos. Letras, dígitos y @/./+/-/_ solamente.', max_length=150, null=True, unique=True),
        ),
    ]
