# Generated by Django 5.2.6 on 2025-10-09 06:33

import core.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Alumno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('matricula', models.CharField(max_length=20, unique=True)),
                ('curp', core.fields.EncryptedCharField(default='N/A', max_length=500)),
                ('rfc', core.fields.EncryptedCharField(default='N/A', max_length=500)),
                ('nombre', models.CharField(max_length=200)),
                ('apellido_paterno', models.CharField(default='N/A', max_length=200)),
                ('apellido_materno', models.CharField(default='N/A', max_length=200)),
                ('municipio_nacimiento', models.CharField(default='N/A', max_length=100)),
                ('fecha_nacimiento', models.DateField(blank=True, null=True)),
                ('sexo', models.CharField(choices=[('hombre', 'Hombre'), ('mujer', 'Mujer'), ('otro', 'Otro')], default='N/A', max_length=10)),
                ('institucion_procedencia', models.CharField(default='N/A', max_length=200)),
                ('municipio_institucion', models.CharField(default='N/A', max_length=100)),
                ('clave_escuela', models.CharField(default='N/A', max_length=50)),
                ('fecha_terminacion_prepa', models.DateField(blank=True, null=True)),
                ('promedio_prepa', models.FloatField(blank=True, null=True)),
                ('constancia_terminacion', models.CharField(choices=[('si', 'Sí'), ('no', 'No'), ('na', 'N/A')], default='na', max_length=2)),
                ('promedio_semestre_anterior', models.FloatField(blank=True, null=True)),
                ('semestre_actual', models.PositiveIntegerField(default=1)),
                ('turno', models.CharField(choices=[('matutino', 'Matutino'), ('vespertino', 'Vespertino')], default='matutino', max_length=20)),
                ('plan', models.PositiveIntegerField(default=2023)),
                ('email_institucional', core.fields.EncryptedEmailField(default='N/A', max_length=500)),
                ('password_email_institucional', core.fields.EncryptedCharField(default='N/A', max_length=500)),
                ('email_personal', core.fields.EncryptedEmailField(default='N/A', max_length=500)),
                ('telefono', core.fields.EncryptedCharField(default='N/A', max_length=500)),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Alumno',
                'verbose_name_plural': 'Alumnos',
                'ordering': ['matricula'],
            },
        ),
    ]
