# Generated by Django 5.2.7 on 2025-10-25 05:33

import alumnos.models
import core.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Alumno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('matricula', models.CharField(default='PENDIENTE', max_length=20)),
                ('curp', core.fields.EncryptedCharField(default='N/A', max_length=500)),
                ('rfc', core.fields.EncryptedCharField(default='N/A', max_length=500)),
                ('nombre', models.CharField(default='N/A', max_length=200)),
                ('apellido_paterno', models.CharField(default='N/A', max_length=200)),
                ('apellido_materno', models.CharField(default='N/A', max_length=200)),
                ('municipio_nacimiento', models.CharField(default='N/A', max_length=100)),
                ('fecha_nacimiento', models.DateField(blank=True, null=True)),
                ('sexo', models.CharField(choices=[('hombre', 'Hombre'), ('mujer', 'Mujer'), ('otro', 'Otro')], default='N/A', max_length=10)),
                ('institucion_procedencia', models.CharField(default='N/A', max_length=200)),
                ('municipio_institucion', models.CharField(default='N/A', max_length=100)),
                ('clave_escuela', models.CharField(default='N/A', max_length=50)),
                ('fecha_terminacion_prepa', models.DateField(blank=True, null=True)),
                ('promedio_prepa', models.FloatField(blank=True, null=True)),
                ('constancia_terminacion', models.CharField(choices=[('si', 'Sí'), ('no', 'No')], default='no', max_length=2)),
                ('promedio_semestre_anterior', models.FloatField(blank=True, null=True)),
                ('semestre_actual', models.PositiveIntegerField(default=1)),
                ('turno', models.CharField(choices=[('matutino', 'Matutino'), ('vespertino', 'Vespertino')], default='matutino', max_length=20)),
                ('plan', models.PositiveIntegerField(default=2023)),
                ('email_institucional', core.fields.EncryptedCharField(default='Pendiente', help_text="Debe terminar con @edubc.mx. Use 'Pendiente' si no tiene correo asignado.", max_length=500, validators=[alumnos.models.validate_email_domain, alumnos.models.validate_email_format])),
                ('password_email_institucional', core.fields.EncryptedCharField(default='N/A', max_length=500)),
                ('email_personal', core.fields.EncryptedCharField(default='N/A', help_text="Use 'N/A' si no tiene correo personal.", max_length=500, validators=[alumnos.models.validate_email_format])),
                ('telefono', core.fields.EncryptedCharField(default='N/A', max_length=500)),
                ('estado', models.CharField(choices=[('activo', 'Activo'), ('inactivo', 'Inactivo'), ('graduado', 'Graduado')], default='activo', max_length=20)),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Alumno',
                'verbose_name_plural': 'Alumnos',
                'ordering': ['matricula', 'apellido_paterno', 'apellido_materno', 'nombre'],
            },
        ),
    ]
