# Generated by Django 5.2.6 on 2025-09-11 20:51

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Alumno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('curp', models.CharField(max_length=18, unique=True, verbose_name='CURP')),
                ('nombre', models.CharField(max_length=100)),
                ('apellido_paterno', models.CharField(max_length=100)),
                ('apellido_materno', models.CharField(max_length=100)),
                ('fecha_nacimiento', models.DateField()),
                ('sexo', models.CharField(choices=[('HOMBRE', 'Hombre'), ('MUJER', 'Mujer')], max_length=10)),
                ('municipio_estado_nacimiento', models.CharField(max_length=100)),
                ('matricula', models.CharField(blank=True, max_length=20, null=True, unique=True)),
                ('licenciatura', models.CharField(choices=[('EDUCACION_ESPECIAL', 'Licenciatura en Educación Especial'), ('INCLUSION_EDUCATIVA', 'Licenciatura en Inclusión Educativa')], max_length=50)),
                ('semestre_actual', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(8)])),
                ('turno', models.CharField(choices=[('MATUTINO', 'Matutino'), ('VESPERTINO', 'Vespertino')], max_length=20)),
                ('promedio_prepa', models.DecimalField(blank=True, decimal_places=1, max_digits=3, null=True)),
                ('institucion_procedencia', models.CharField(max_length=200)),
                ('correo_particular', models.EmailField(blank=True, max_length=254, null=True)),
                ('numero_celular', models.CharField(blank=True, max_length=15, null=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Alumno',
                'verbose_name_plural': 'Alumnos',
                'ordering': ['apellido_paterno', 'apellido_materno', 'nombre'],
            },
        ),
    ]
