# Generated by Django 5.2.6 on 2025-09-12 22:08

import core.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('alumnos', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='alumno',
            name='fecha_nacimiento',
        ),
        migrations.AlterField(
            model_name='alumno',
            name='apellido_materno',
            field=core.fields.EncryptedCharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='alumno',
            name='apellido_paterno',
            field=core.fields.EncryptedCharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='alumno',
            name='correo_particular',
            field=core.fields.EncryptedEmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='alumno',
            name='curp',
            field=core.fields.EncryptedCharField(max_length=18, unique=True, verbose_name='CURP'),
        ),
        migrations.AlterField(
            model_name='alumno',
            name='municipio_estado_nacimiento',
            field=core.fields.EncryptedCharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='alumno',
            name='nombre',
            field=core.fields.EncryptedCharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='alumno',
            name='numero_celular',
            field=core.fields.EncryptedCharField(blank=True, max_length=15, null=True),
        ),
    ]
