# Generated by Django 5.2.6 on 2025-09-12 22:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alumnos', '0002_remove_alumno_fecha_nacimiento_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='alumno',
            name='fecha_nacimiento',
            field=models.DateField(default='2006-12-28'),
            preserve_default=False,
        ),
    ]
