# Generated by Django 5.2.6 on 2025-10-12 05:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alumnos', '0002_initial'),
        ('evaluaciones', '0005_alter_materia_creditos_alter_materia_horas'),
    ]

    operations = [
        migrations.AddField(
            model_name='alumno',
            name='estado',
            field=models.CharField(choices=[('activo', 'Activo'), ('inactivo', 'Inactivo'), ('graduado', 'Graduado')], default='activo', max_length=20),
        ),
        migrations.AlterField(
            model_name='alumno',
            name='carrera',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='evaluaciones.carrera'),
        ),
        migrations.AlterField(
            model_name='alumno',
            name='constancia_terminacion',
            field=models.CharField(choices=[('si', 'Sí'), ('no', 'No')], default='no', max_length=2),
        ),
        migrations.AlterField(
            model_name='alumno',
            name='matricula',
            field=models.CharField(default='PENDIENTE', max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='alumno',
            name='nombre',
            field=models.CharField(default='N/A', max_length=200),
        ),
    ]
