# Generated by Django 5.2.6 on 2025-10-12 06:37

import alumnos.models
import core.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('alumnos', '0003_alumno_estado_alter_alumno_carrera_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alumno',
            name='email_institucional',
            field=core.fields.EncryptedCharField(default='Pendiente', help_text="Debe terminar con @edubc.mx. Use 'Pendiente' si no tiene correo asignado.", max_length=500, validators=[alumnos.models.validate_email_domain, alumnos.models.validate_email_format]),
        ),
        migrations.AlterField(
            model_name='alumno',
            name='email_personal',
            field=core.fields.EncryptedCharField(default='N/A', help_text="Use 'N/A' si no tiene correo personal.", max_length=500, validators=[alumnos.models.validate_email_format]),
        ),
    ]
