# Generated by Django 5.2.6 on 2025-09-12 22:26

import core.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('alumnos', '0003_alumno_fecha_nacimiento'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alumno',
            name='institucion_procedencia',
            field=core.fields.EncryptedCharField(max_length=200),
        ),
    ]
