# Generated by Django 5.2.6 on 2025-09-12 22:27

import core.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('alumnos', '0004_alter_alumno_institucion_procedencia'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alumno',
            name='apellido_materno',
            field=core.fields.EncryptedCharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='alumno',
            name='apellido_paterno',
            field=core.fields.EncryptedCharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='alumno',
            name='curp',
            field=core.fields.EncryptedCharField(max_length=255, unique=True, verbose_name='CURP'),
        ),
        migrations.AlterField(
            model_name='alumno',
            name='institucion_procedencia',
            field=core.fields.EncryptedCharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='alumno',
            name='municipio_estado_nacimiento',
            field=core.fields.EncryptedCharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='alumno',
            name='nombre',
            field=core.fields.EncryptedCharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='alumno',
            name='numero_celular',
            field=core.fields.EncryptedCharField(blank=True, max_length=255, null=True),
        ),
    ]
